package org.lwjgl.util.jinput;

import net.java.games.input.Component.Identifier.Key;

final class KeyMap {
    KeyMap() {
    }

    public static Key map(int i) {
        switch (i) {
            case 1:
                return Key.ESCAPE;
            case 2:
                return Key.f89_1;
            case 3:
                return Key.f90_2;
            case 4:
                return Key.f91_3;
            case 5:
                return Key.f92_4;
            case 6:
                return Key.f93_5;
            case 7:
                return Key.f94_6;
            case 8:
                return Key.f95_7;
            case 9:
                return Key.f96_8;
            case 10:
                return Key.f97_9;
            case 11:
                return Key.f88_0;
            case 12:
                return Key.MINUS;
            case 13:
                return Key.EQUALS;
            case 14:
                return Key.BACK;
            case 15:
                return Key.TAB;
            case 16:
                return Key.f77Q;
            case 17:
                return Key.f84W;
            case 18:
                return Key.f56E;
            case 19:
                return Key.f78R;
            case 20:
                return Key.f80T;
            case 21:
                return Key.f86Y;
            case 22:
                return Key.f81U;
            case 23:
                return Key.f69I;
            case 24:
                return Key.f75O;
            case 25:
                return Key.f76P;
            case 26:
                return Key.LBRACKET;
            case 27:
                return Key.RBRACKET;
            case 28:
                return Key.RETURN;
            case 29:
                return Key.LCONTROL;
            case 30:
                return Key.f50A;
            case 31:
                return Key.f79S;
            case 32:
                return Key.f55D;
            case 33:
                return Key.f57F;
            case 34:
                return Key.f67G;
            case 35:
                return Key.f68H;
            case 36:
                return Key.f70J;
            case 37:
                return Key.f71K;
            case 38:
                return Key.f72L;
            case 39:
                return Key.SEMICOLON;
            case 40:
                return Key.APOSTROPHE;
            case 41:
                return Key.GRAVE;
            case 42:
                return Key.LSHIFT;
            case 43:
                return Key.BACKSLASH;
            case 44:
                return Key.f87Z;
            case 45:
                return Key.f85X;
            case 46:
                return Key.f54C;
            case 47:
                return Key.f83V;
            case 48:
                return Key.f53B;
            case 49:
                return Key.f74N;
            case 50:
                return Key.f73M;
            case 51:
                return Key.COMMA;
            case 52:
                return Key.PERIOD;
            case 53:
                return Key.SLASH;
            case 54:
                return Key.RSHIFT;
            case 55:
                return Key.MULTIPLY;
            case 56:
                return Key.LALT;
            case 57:
                return Key.SPACE;
            case 58:
                return Key.CAPITAL;
            case 59:
                return Key.f58F1;
            case 60:
                return Key.f59F2;
            case 61:
                return Key.f60F3;
            case 62:
                return Key.f61F4;
            case 63:
                return Key.f62F5;
            case 64:
                return Key.f63F6;
            case 65:
                return Key.f64F7;
            case 66:
                return Key.f65F8;
            case 67:
                return Key.f66F9;
            case 68:
                return Key.F10;
            case 69:
                return Key.NUMLOCK;
            case 70:
                return Key.SCROLL;
            case 71:
                return Key.NUMPAD7;
            case 72:
                return Key.NUMPAD8;
            case 73:
                return Key.NUMPAD9;
            case 74:
                return Key.SUBTRACT;
            case 75:
                return Key.NUMPAD4;
            case 76:
                return Key.NUMPAD5;
            case 77:
                return Key.NUMPAD6;
            case 78:
                return Key.ADD;
            case 79:
                return Key.NUMPAD1;
            case 80:
                return Key.NUMPAD2;
            case 81:
                return Key.NUMPAD3;
            case 82:
                return Key.NUMPAD0;
            case 83:
                return Key.DECIMAL;
            case 87:
                return Key.F11;
            case 88:
                return Key.F12;
            case 100:
                return Key.F13;
            case 101:
                return Key.F14;
            case 102:
                return Key.F15;
            case 112:
                return Key.KANA;
            case 121:
                return Key.CONVERT;
            case 123:
                return Key.NOCONVERT;
            case 125:
                return Key.YEN;
            case 141:
                return Key.NUMPADEQUAL;
            case 144:
                return Key.CIRCUMFLEX;
            case 145:
                return Key.f51AT;
            case 146:
                return Key.COLON;
            case 147:
                return Key.UNDERLINE;
            case 148:
                return Key.KANJI;
            case 149:
                return Key.STOP;
            case 150:
                return Key.f52AX;
            case 151:
                return Key.UNLABELED;
            case 156:
                return Key.NUMPADENTER;
            case 157:
                return Key.RCONTROL;
            case 179:
                return Key.NUMPADCOMMA;
            case 181:
                return Key.DIVIDE;
            case 183:
                return Key.SYSRQ;
            case 184:
                return Key.RALT;
            case 197:
                return Key.PAUSE;
            case 199:
                return Key.HOME;
            case 200:
                return Key.f82UP;
            case 201:
                return Key.PAGEUP;
            case 203:
                return Key.LEFT;
            case 205:
                return Key.RIGHT;
            case 207:
                return Key.END;
            case 208:
                return Key.DOWN;
            case 209:
                return Key.PAGEDOWN;
            case 210:
                return Key.INSERT;
            case 211:
                return Key.DELETE;
            case 219:
                return Key.LWIN;
            case 220:
                return Key.RWIN;
            case 221:
                return Key.APPS;
            case 222:
                return Key.POWER;
            case 223:
                return Key.SLEEP;
            default:
                return Key.UNKNOWN;
        }
    }
}
